services:
  web:
    build: .
    container_name: qwmc-website
    restart: always
    ports:
      - "127.0.0.1:8080:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./public:/app/public 