services:
  # web:
  #   build: .
  #   container_name: qwmc-website
  #   restart: always
  #   ports:
  #     - "127.0.0.1:8080:3000"
  #   environment:
  #     - NODE_ENV=production
  #   volumes:
  #     - ./public:/app/public
  #   depends_on:
  #     - db
  db:
    image: mariadb:11
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: qwmc_db
      MYSQL_USER: qwmc
      MYSQL_PASSWORD: qwmc_password
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data: 